# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  izi_config = debug
  tests_config = debug

else ifeq ($(config),release)
  izi_config = release
  tests_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := izi tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

izi:
ifneq (,$(izi_config))
	@echo "==== Building izi ($(izi_config)) ===="
	@${MAKE} --no-print-directory -C . -f izi.make config=$(izi_config)
endif

tests:
ifneq (,$(tests_config))
	@echo "==== Building tests ($(tests_config)) ===="
	@${MAKE} --no-print-directory -C tests -f Makefile config=$(tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f izi.make clean
	@${MAKE} --no-print-directory -C tests -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   izi"
	@echo "   tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"