#pragma once

#include "chunk.hpp"
#include <string>
#include <ostream>

namespace izi {

// Disassembler: converts a bytecode Chunk into a human-readable listing.
// Used during VM development to inspect and verify generated bytecode.
class Disassembler {
   public:
    // Disassemble the entire chunk, writing to the given stream.
    // 'name' is a label displayed in the header (e.g. function name).
    static void disassemble(const Chunk& chunk, const std::string& name, std::ostream& out);

    // Disassemble a single instruction at 'offset' and return the offset of the
    // next instruction. Writes the disassembly of that instruction to 'out'.
    static size_t disassembleInstruction(const Chunk& chunk, size_t offset, std::ostream& out);
};

}  // namespace izi
